version: '3.8'

services:
  app:
    image: eclipse-temurin:21-jdk-alpine
    container_name: abertamente_java_app
    working_dir: /app
    volumes:
      - .:/app
      - gradle_cache:/root/.gradle
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    command: ["./gradlew", "bootRun"]

  mailpit:
    image: axllent/mailpit
    container_name: abertamente_mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 500
volumes:
  gradle_cache:
